### PR TITLE
Enhancement: Include OEM Part Number and Device ID in MQTT Discovery Message

### PR DESCRIPTION
**Pull request by genestealer**
**Inclusion of OEM Part Number in Device JSON Files:**
I've implemented a modification to include the OEM Part Number in the device JSON files. This enhancement aims to provide comprehensive information about each device, aiding in identification within the system.

**JSON Beautification for Future Collaborations:**
In conjunction with these changes, I've applied a JSON beautifier to the device JSON files. This step ensures enhanced readability and facilitates easier implementation of one-line changes in future collaborations.

**Appending Device ID and Part Number to MQTT Discovery Message:**
I've extended the functionality by appending both the Device ID and OEM Part Number to the Device Model field in the MQTT discovery message. Previously, the Device ID was included only in the Name, but this information was lost if the user decided to rename the device. This adjustment ensures that identification details persist even if the user chooses to customize the device name.

**Consideration for Google Assistant Interaction:**
I have a preference for being aware of the Device ID for my devices, especially as I physically label them. However, I aim to avoid the Device ID becoming a part of the Device "Name." This is crucial to prevent complications when interacting with Google Assistant, as it may read out the Device ID in a long format, such as "fifty-two thousand and twenty-three," along with the custom name. Such instances can lead to less user-friendly interactions.

With the new implementation, the Device ID and Part Number are integrated into the Model details in Home Assistant. This allows me to maintain visibility of this information while customizing the device name. For instance, I can rename a device from "dehumidifier 5223" to simply "dehumidifier."

### CODE REVIEW

**Comment by Achronite** [comment]
Can you give an example of how this now looks in HA (before any manual edits) please?

(merging on my test pi may be tricky until I finish helping get the thermostat working)

**Comment by genestealer** [comment]
Some extra photos:
image


Note the entity ID is unchanged, in this example. But for most people they would say yes and auto-rename all the entity ID's.
image

**Comment by genestealer** [comment]
> serial_number

Thank you, yes I can remove 18.json to make it a cleaner merge. 

Can you clarify your question on serial_number?  The current proposed change shows it as `Radiator (MIHO013) [4329]`

image

**Comment by Achronite** [comment]
> Can you clarify your question on serial_number? The current proposed change shows it as `Radiator (MIHO013) [4329]`

Your proposed change adds the device address to the 'model' property; which is really designed to store the generic model details of the device. `serial_number` can be used to identify the different devices for that model in the [device registry](https://developers.home-assistant.io/docs/device_registry_index/#device-properties); but it isn't listed in the MQTT discovery manual; so I'm not entirely sure we can use it...  I was wondering if you have tried?

**Comment by genestealer** [comment]
> > Can you clarify your question on serial_number? The current proposed change shows it as `Radiator (MIHO013) [4329]`
> 
> Your proposed change adds the device address to the 'model' property; which is really designed to store the generic model details of the device. `serial_number` can be used to identify the different devices for that model in the [device registry](https://developers.home-assistant.io/docs/device_registry_index/#device-properties); but it isn't listed in the MQTT discovery manual; so I'm not entirely sure we can use it... I was wondering if you have tried?

Oh, I did not know about that, not sure the serial number would show up on the GUI. I will have to give it a try on the MQTT discovery. 

Out of interested, I tried it on the Manually configured MQTT entities, and it gave an error.

image

**Comment by Achronite** [comment]
> Out of interested, I tried it on the Manually configured MQTT entities, and it gave an error.

OK, it's unlikely to work in the current version of MQTT discovery then.

**Comment by genestealer** [comment]
> OK, it's unlikely to work in the current version of MQTT discovery then.
> 
> BTW: I'm still seeing conflicts for 18.json

Tested it also with MQTT discovery, with no joy

image

**Comment by Achronite** [comment]
> Tested it also with MQTT discovery, with no joy

OK no problems.  If you get the conflict resolved on 18.json (maybe try downloading the latest version), then I'll merge it.

image

**Comment by genestealer** [comment]
@Achronite Updated and ready for your review.

**Review by Achronite — APPROVED** [review]

**Pull request merged**
