### PR TITLE
Develop v0.6.0 Release

### LINKED ISSUE #46: Merge/contribute project efforts
Hi, firstly this is fantastic work and thank you for making this. :)

I would migrate over from my node-red instance (using node-red-contrib-energenie-ener314rt) to mqtt-energenie-ener314rt but I notice I added some extra functionality into my MQTT discovery on node-red, which I would like to suggest we add into this.

My repo: https://github.com/genestealer/node-red-energenie-ener314rt-home-assistant-mqtt

Happy to make all the changes and then submit a pull request.

3. Smart Plug Plus (MIHO005) and Smart Monitor Plug (MIHO004) don't seem to be reporting all their data on your code:
Mine:
image
Yours:
image

### PR DESCRIPTION
**Pull request by Achronite**
Closes #46, #47, #49, #52

### CODE REVIEW

**Comment by Achronite** [comment]
@genestealer Thank you for all your help, it is much appreciated. :-)

Can you give the code a quick once over please to ensure your agreed changes have been added as discussed?

**Comment by genestealer** [comment]
Brilliant, thank you. I will have a look shortly.

**Review by genestealer — APPROVED** [review]
The code looks great and appears to be ready for merging. I recommend considering running the entire code through a code beautifier. This process will expand the condensed code into separate lines, enhancing the readability and making it easier to compare differences in future revisions.

**Comment by genestealer** [comment]
@Achronite everything ok?

**Comment by Achronite** [comment]
Yeah, I'm OK just far too busy at the moment.  I'll try and get this released soon.

**Comment by genestealer** [comment]
No worries at all.
You might see that I've raised another PR as well, to leverage the config
file to set the default enable or disabled behaviour on the frequency and
voltage reporting.

**Pull request merged**
